/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package adventOfCode

import adventOfCode.Day1.getClass
import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

import java.io.FileNotFoundException
import scala.io.Source
import scala.reflect.internal.util.NoPosition.line
import scala.util.Try

@RunWith(classOf[JUnitRunner])
class CodeOfAdventTests extends AnyFunSuite {
  test("App has a greeting") {
    assert(App.greeting() != null)
  }

  test("Test sample input") {
    val fileStream = getClass.getResourceAsStream("/Day1Sample.txt")
    val counter = Day1.sonarSweep(Source.fromInputStream(fileStream).getLines)
    assert(counter == 7)
    println("Counter is: " + counter)
  }

  test("Calculate Actual Input Test") {
    val fileStream = getClass.getResourceAsStream("/Day1Actual.txt")
    val counter = Day1.sonarSweep(Source.fromInputStream(fileStream).getLines)
    assert(counter == 1387)
    println("Counter is: " + counter)
  }
  

}
