/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.topherian.adventOfCode

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

import scala.io.Source

@RunWith(classOf[JUnitRunner])
class Day1Tests extends AnyFunSuite {

  test("Test sample input") {
    val fileStream = getClass.getResourceAsStream("/Day1Sample.txt")
    val counter = Day1.sonarSweep(Source.fromInputStream(fileStream).getLines.toList.map((s: String) => s.toInt))
    assert(counter == 7)
    println("Counter is: " + counter)
  }

  test("Calculate Actual Input Test") {
    val fileStream = getClass.getResourceAsStream("/Day1Actual.txt")
    val counter = Day1.sonarSweep(Source.fromInputStream(fileStream).getLines.toList.map((s: String) => s.toInt))
    assert(counter == 1387)
    println("Counter is: " + counter)
  }

  test("Calculate sliding windows with Sample input") {
    val fileStream = getClass.getResourceAsStream("/Day1Sample.txt")
    val lines: List[Int] = Source.fromInputStream(fileStream).getLines().toList.map((s: String) => s.toInt)
    val counter: Int = Day1.slidingSonarSweep(lines, 3)
    assert(counter == 5)
  }

  test("Calculate sliding windows with Actual input") {
    val fileStream = getClass.getResourceAsStream("/Day1Actual.txt")
    val lines: List[Int] = Source.fromInputStream(fileStream).getLines().toList.map((s: String) => s.toInt)
    val counter: Int = Day1.slidingSonarSweep(lines, 3)
    assert(counter == 1362)
  }
}
