/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.topherian.adventOfCode

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class Day2Tests extends AnyFunSuite {

}
